"""add last_login_at to user model

Revision ID: 0d839d8237a7
Revises: ad3f04c48711
Create Date: 2025-07-15 23:07:02.831381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d839d8237a7'
down_revision: Union[str, None] = 'ad3f04c48711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
